"""Assembly helpers for robot CAD generation."""

from .cq_adapter import (
    CadQueryConstraintCall,
    apply_cadquery_constraint_calls,
    apply_layout_constraints_to_assembly,
    build_cadquery_constraint_calls,
    build_layout_cadquery_constraint_calls,
)
from .constraints import (
    AssemblyMateConstraintPlan,
    AssemblyMateConstraintRule,
    CadQueryAssemblyConstraintPlan,
    CadQueryAssemblyConstraintRule,
    build_assembly_mate_constraint_plan,
    build_assembly_mate_constraint_rules,
    build_cadquery_assembly_constraint_plan,
    build_cadquery_assembly_constraint_rules,
    normalize_constraint_kind,
)
from .constraint_graph import (
    ConstraintGraphEdge,
    ConstraintGraphReport,
    FullAssemblySolveGate,
    FullAssemblySolveGateStatus,
    LocalSubassemblyConstraintGraph,
    WholeAssemblyConstraintGraph,
    build_constraint_graph_report,
    build_local_subassembly_constraint_graph,
    build_whole_assembly_constraint_graph,
    evaluate_full_assembly_solve_gate,
)
from .compiler import (
    AssemblyCompileConflict,
    AssemblyCompilerResult,
    compile_assembly_plan,
)
from .features import (
    CadQueryMateFeatureCatalog,
    CadQueryMateFeatureRule,
    build_cadquery_mate_feature_catalog,
    build_cadquery_mate_feature_rules,
    tag_workplane_feature,
)
from .mate_frames import (
    MateFrame,
    MateFrameCatalog,
    build_mate_frame_catalog,
    build_mate_frames,
)
from .local_solve import (
    LocalSubassemblyPlan,
    LocalSubassemblySpec,
    build_local_subassembly_plans,
    default_local_subassembly_specs,
)
from .local_promotion import (
    LocalSubassemblyPromotionMetrics,
    build_local_subassembly_promotion_report,
    local_subassembly_is_promotion_ready,
    local_subassembly_promotion_metrics,
    ready_local_subassembly_names,
)
from .plan import (
    AssemblyChain,
    AssemblyMate,
    AssemblyOccurrence,
    AssemblyPlan,
    PartDatum,
    build_assembly_plan,
)

__all__ = [
    "AssemblyChain",
    "AssemblyCompileConflict",
    "AssemblyCompilerResult",
    "AssemblyMate",
    "AssemblyMateConstraintPlan",
    "AssemblyMateConstraintRule",
    "AssemblyOccurrence",
    "AssemblyPlan",
    "CadQueryAssemblyConstraintPlan",
    "CadQueryAssemblyConstraintRule",
    "CadQueryConstraintCall",
    "CadQueryMateFeatureCatalog",
    "CadQueryMateFeatureRule",
    "ConstraintGraphEdge",
    "ConstraintGraphReport",
    "FullAssemblySolveGate",
    "FullAssemblySolveGateStatus",
    "MateFrame",
    "MateFrameCatalog",
    "PartDatum",
    "LocalSubassemblyConstraintGraph",
    "WholeAssemblyConstraintGraph",
    "LocalSubassemblyPlan",
    "LocalSubassemblyPromotionMetrics",
    "LocalSubassemblySpec",
    "apply_cadquery_constraint_calls",
    "apply_layout_constraints_to_assembly",
    "build_assembly_mate_constraint_plan",
    "build_assembly_mate_constraint_rules",
    "build_assembly_plan",
    "compile_assembly_plan",
    "build_cadquery_assembly_constraint_plan",
    "build_cadquery_assembly_constraint_rules",
    "build_cadquery_constraint_calls",
    "build_constraint_graph_report",
    "evaluate_full_assembly_solve_gate",
    "build_layout_cadquery_constraint_calls",
    "build_local_subassembly_constraint_graph",
    "build_whole_assembly_constraint_graph",
    "build_local_subassembly_promotion_report",
    "build_mate_frame_catalog",
    "build_mate_frames",
    "build_local_subassembly_plans",
    "default_local_subassembly_specs",
    "local_subassembly_is_promotion_ready",
    "local_subassembly_promotion_metrics",
    "ready_local_subassembly_names",
    "build_cadquery_mate_feature_catalog",
    "build_cadquery_mate_feature_rules",
    "normalize_constraint_kind",
    "tag_workplane_feature",
]
